# Author: Greedysky <greedysky@163.com>

name: win7

on: workflow_call

env:
  TTK_MODULE: TTKWidgetTools
  TTK_VERSION: 3.1.0.0

jobs:
  build:
    name: Build on Qt5
    strategy:
      matrix:
        arch: [32, 64]
        os: [windows-2022]
        include:
          - arch: 32
            target: x86
            collection: libgcc_s_dw2-1

          - arch: 64
            target: x64
            collection: libgcc_s_seh-1

    env:
      QT_VERSION: 5.15.18
      QT_ROOT_DIR: D:/a/TTKWidgetTools/Qt/5.15.18/mingw810_${{matrix.arch}}
      QT_BIN_DIR: D:/a/TTKWidgetTools/Qt/5.15.18/mingw810_${{matrix.arch}}/bin
      MINGW_PATH: D:/a/TTKWidgetTools/mingw/bin

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        run: |
          curl -L https://github.com/Greedysky/buildQt/releases/download/5.15.18/Qt_5.15.18-shared-release_mingw810_${{matrix.arch}}.7z -o Qt.7z
          7z x Qt.7z -oQt
          mv Qt/5.15.18-shared Qt/5.15.18
          # set environment variable
          echo "${{env.QT_BIN_DIR}};" >> $env:GITHUB_PATH
        working-directory: ${{runner.workspace}}

      - name: Install MinGW810_${{matrix.arch}}
        run: |
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/mingw810_${{matrix.arch}}.7z -o mingw.7z
          7z x mingw.7z -omingw
          # remove default installed mingw64
          mv C:\mingw64 C:\mingw64_useless
          # set environment variable
          echo "${{env.MINGW_PATH}};" >> $env:GITHUB_PATH
        working-directory: ${{runner.workspace}}

      - name: Create build dir
        shell: bash
        run: mkdir build
        working-directory: ${{runner.workspace}}

      - name: Build project
        run: |
          qmake -v
          cmake --version
          cmake ${{github.workspace}} -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DCMAKE_PREFIX_PATH=${{env.QT_ROOT_DIR}} -DTTK_QT_VERSION=5
          mingw32-make -j2 && mingw32-make install
        working-directory: ${{runner.workspace}}/build

      - name: Build package
        run: |
          # add dependency for openssl
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/openssl.7z -o openssl.7z
          7z x openssl.7z
          cp win${{matrix.arch}}/*.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          # add dependency libraries and so on
          windeployqt ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}/${{env.TTK_MODULE}}.exe
          cp ${{env.QT_BIN_DIR}}/Qt5Xml.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          # remove useless library dependency
          ls -Filter "*.a" -Recurse | Remove-Item -Force
          rm ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}/translations -Recurse
          # add portable binary package
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-win7-${{matrix.target}}.7z ${{env.TTK_MODULE}}
        working-directory: ${{runner.workspace}}/install

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: ${{runner.workspace}}/install/${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-win7-${{matrix.target}}.7z
