# Author: Greedysky <greedysky@163.com>

name: winXP-mingw

on: workflow_call

env:
  TTK_MODULE: TTKWidgetTools
  TTK_VERSION: 3.1.0.0

jobs:
  build:
    name: Build on Qt4
    strategy:
      matrix:
        os: [windows-2022]

    env:
      QT_VERSION: 4.8.7
      QT_ROOT_DIR: D:/a/TTKWidgetTools/Qt/4.8.7
      MINGW_PATH: D:/a/TTKWidgetTools/mingw/bin

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        run: |
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/Qt4.7z -o Qt.7z
          7z x Qt.7z -oQt
          "[Paths]`nPrefix = ${{env.QT_ROOT_DIR}}" > ${{env.QT_ROOT_DIR}}/bin/qt.conf
          echo "${{env.QT_ROOT_DIR}}/bin;" >> $env:GITHUB_PATH
        working-directory: ${{runner.workspace}}

      - name: Install MinGW492_32
        run: |
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/mingw492_32.7z -o mingw.7z
          7z x mingw.7z -omingw
          # remove default installed mingw64
          mv C:\mingw64 C:\mingw64_useless
          # set environment variable
          echo "${{env.MINGW_PATH}};" >> $env:GITHUB_PATH
        working-directory: ${{runner.workspace}}

      - name: Create build dir
        run: mkdir build
        working-directory: ${{runner.workspace}}

      - name: Build project
        run: |
          qmake -v
          cmake --version
          cmake ${{github.workspace}} -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DCMAKE_PREFIX_PATH=${{env.QT_ROOT_DIR}} -DTTK_QT_VERSION=4 -DQT_MOC_EXECUTABLE=${{env.QT_ROOT_DIR}}/bin/moc.exe -DQT_RCC_EXECUTABLE=${{env.QT_ROOT_DIR}}/bin/rcc.exe -DQT_UIC_EXECUTABLE=${{env.QT_ROOT_DIR}}/bin/uic.exe
          mingw32-make -j2 && mingw32-make install
        working-directory: ${{runner.workspace}}/build

      - name: Build package
        run: |
          # add dependency for openssl
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/openssl.7z -o openssl.7z
          7z x openssl.7z
          cp win32/v0/*.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          # add dependency libraries and so on
          cp ${{env.QT_ROOT_DIR}}/plugins/bearer ${{env.TTK_MODULE}}/${{env.TTK_VERSION}} -Recurse -Container -Force
          cp ${{env.QT_ROOT_DIR}}/plugins/iconengines ${{env.TTK_MODULE}}/${{env.TTK_VERSION}} -Recurse -Container -Force
          cp ${{env.QT_ROOT_DIR}}/plugins/imageformats ${{env.TTK_MODULE}}/${{env.TTK_VERSION}} -Recurse -Container -Force
          cp ${{env.QT_ROOT_DIR}}/bin/QtCore4.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          cp ${{env.QT_ROOT_DIR}}/bin/QtGui4.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          cp ${{env.QT_ROOT_DIR}}/bin/QtNetwork4.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          cp ${{env.QT_ROOT_DIR}}/bin/QtSvg4.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          cp ${{env.QT_ROOT_DIR}}/bin/QtXml4.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          cp ${{env.MINGW_PATH}}/libstdc++-6.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          cp ${{env.MINGW_PATH}}/libwinpthread-1.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          cp ${{env.MINGW_PATH}}/libgcc_s_dw2-1.dll ${{env.TTK_MODULE}}/${{env.TTK_VERSION}}
          # remove useless library dependency
          ls -Filter "*.a" -Recurse | Remove-Item -Force
          # add portable binary package
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-winXP-mingw-x86.7z ${{env.TTK_MODULE}}
        working-directory: ${{runner.workspace}}/install

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: ${{runner.workspace}}/install/${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-winXP-mingw-x86.7z
